export const QUESTIONS_FETCH_REQUEST = 'QUESTIONS_FETCH_REQUEST';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const ANSWER_SELECTED = 'ANSWER_SELECTED';
export const GAME_RESET = 'GAME_RESET';
